version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.27
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.35
    - 14.14.37
    - 15.0.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
